 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Reyavaya_Technologies_;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import javax.swing.Icon;
import Reyavaya_Technologies_.Reyavaya_Tech;
import java.sql.*;

/**
 *
 * @author Daniel Khoza
 */
public class Reyavaya_Login extends javax.swing.JFrame {
    
    public Reyavaya_Login Reyavayalogin;
    public Reyavaya_Tech reyavayatech;
    private int counter = 5;
    
    public ImageIcon icon;

    /**
     * Creates new form Reyavaya_Login
     */
    public Reyavaya_Login() {
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/3, dim.height/4);
        
        initComponents();
        String fp = "<html><u> Forgot Password? </u></html>";
        ForgotPassword.setText(fp);
        reyavayatech = new Reyavaya_Tech();
        setIconImage();
    }
    
    private void setIconImage(){
    setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icons8-motherboard-100.png"))); 
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnExit1 = new javax.swing.JButton();
        txtUser = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        btnEnter = new javax.swing.JButton();
        ForgotPassword = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REYAVAYA LOGIN");
        setAutoRequestFocus(false);
        setForeground(new java.awt.Color(102, 102, 102));
        setIconImage(getIconImage());
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("User");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 90, 40, 20);

        jLabel4.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Password");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 120, 70, 20);

        btnExit1.setBackground(new java.awt.Color(255, 255, 255));
        btnExit1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        btnExit1.setForeground(new java.awt.Color(0, 0, 0));
        btnExit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exit.png"))); // NOI18N
        btnExit1.setText("EXIT");
        btnExit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit1);
        btnExit1.setBounds(260, 180, 150, 30);

        txtUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUserMouseClicked(evt);
            }
        });
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        jPanel1.add(txtUser);
        txtUser.setBounds(80, 90, 330, 25);

        password.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                passwordMouseEntered(evt);
            }
        });
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel1.add(password);
        password.setBounds(80, 120, 330, 25);

        btnEnter.setBackground(new java.awt.Color(255, 255, 255));
        btnEnter.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        btnEnter.setForeground(new java.awt.Color(0, 0, 0));
        btnEnter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-forgot-password-20.png"))); // NOI18N
        btnEnter.setText("ENTER");
        btnEnter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });
        jPanel1.add(btnEnter);
        btnEnter.setBounds(80, 180, 150, 30);

        ForgotPassword.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        ForgotPassword.setForeground(new java.awt.Color(0, 0, 0));
        ForgotPassword.setText("Forgot Password?");
        ForgotPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ForgotPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ForgotPasswordMouseClicked(evt);
            }
        });
        jPanel1.add(ForgotPassword);
        ForgotPassword.setBounds(200, 140, 100, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user1.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 0, 80, 90);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(-10, 0, 500, 250);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        
    }//GEN-LAST:event_passwordActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        
    }//GEN-LAST:event_txtUserActionPerformed

    private void btnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit1ActionPerformed
        ImageIcon Icon = new javax.swing.ImageIcon(getClass().getResource("/Exit1.png"));
        int response = JOptionPane.showConfirmDialog(null,"Do you want to Exit the Application? " , "CONFIRM", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, Icon);
        if(response== JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
        else if(response== JOptionPane.NO_OPTION){
            Reyavayalogin.setVisible(true);
        }
    }//GEN-LAST:event_btnExit1ActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        
        String username = txtUser.getText();
        String pass = password.getText();
                
        if (username.contains("Admin") && (pass.contains("12345"))){
            txtUser.setText(null);
            password.setText(null);
            
            systemExit();
            
            ImageIcon Icon = new javax.swing.ImageIcon(getClass().getResource("/icons8-checked-60.png"));
            JOptionPane.showMessageDialog(this, "Welcome To Reyavaya Technologies !! ", "SUCCESSFULL", JOptionPane.WARNING_MESSAGE, Icon);
            
            this.toBack();
            reyavayatech.setVisible(true);
            reyavayatech.toFront();
            this.hide();       
        }
        else{
            txtUser.setText(null);
            password.setText(null);   
            
            /*lblOutput.setText(String.valueOf("Invalid Password or Username!" ));
            lblOutput2.setText(String.valueOf("Attempts left: " + counter));*/
            
            JOptionPane.showMessageDialog(null,"ERROR!! \n Invalid Password or Username! \n" + "Attempts left:" + counter, "ERROR", JOptionPane.ERROR_MESSAGE);
            
            counter--;
                if(counter == 0) {
                    JOptionPane.showMessageDialog(null,"NO MORE ATTEMPTS LEFT", "ERROR", JOptionPane.ERROR_MESSAGE);
                    btnEnter.setEnabled(false);
                    }
            Reyavayalogin.setVisible(true);
        }
        this.toBack();
        reyavayatech.toFront();
    }//GEN-LAST:event_btnEnterActionPerformed

    private void ForgotPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgotPasswordMouseClicked
        ImageIcon Icon = new javax.swing.ImageIcon(getClass().getResource("/icons8-forgot-password-30.png"));
        JOptionPane.showMessageDialog(this, "Please Contact the Management Team \n" + "To Confirm Your Identity \n" + "\n" + "Tell: 011-562" , "WARNING !!", 
                JOptionPane.WARNING_MESSAGE, Icon);
        txtUser.setText(null);
        password.setText(null);
        
    }//GEN-LAST:event_ForgotPasswordMouseClicked

    private void txtUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserMouseClicked
        
    }//GEN-LAST:event_txtUserMouseClicked

    private void passwordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseEntered

    }//GEN-LAST:event_passwordMouseEntered

    private void passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseClicked
        
    }//GEN-LAST:event_passwordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reyavaya_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reyavaya_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reyavaya_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reyavaya_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reyavaya_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ForgotPassword;
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnExit1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

private void systemExit(){
    WindowEvent winClosing = new WindowEvent (this, WindowEvent.WINDOW_CLOSING); 
}

    private void close() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
}
